const proyects = [
    {
        name: 'calculator',
        image: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
        github:'bla bal bla',
        page:'https://google.com'
    },
    {
        name: 'calculator',
        image: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
        github:'bla bal bla',
        page:'https://google.com'
    },{
        name: 'calculator',
        image: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
        github:'bla bal bla',
        page:'https://google.com'
    },
    {
        name: 'calculator',
        image: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
        github:'bla bal bla',
        page:'https://google.com'
    },{
        name: 'calculator',
        image: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
        github:'bla bal bla',
        page:'https://google.com'
    },
    {
        name: 'calculator',
        image: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
        github:'bla bal bla',
        page:'https://google.com'
    },{
        name: 'calculator',
        image: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
        github:'bla bal bla',
        page:'https://google.com'
    },
    {
        name: 'calculator',
        image: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
        github:'bla bal bla',
        page:'https://google.com'
    },
]

export default proyects;